Добавил код.
vasiliy-kotov/checking_resources_tg_bot pull request #2
Opened 2023-12-20 14:33 UTC by vasiliy-kotov

2024-01-04 00:10 UTC, Arsennikum commented on setup.cfg
> +max-complexity = 10
лучше добавлять пробел в конце) https://semakin.dev/2020/05/no_newline_at_end_of_file/

2024-01-04 00:10 UTC, Arsennikum commented on README.md
> +Перечень зависимостей:
зависимости указаны достаточно удобно в requirements.txt. Здесь их дополнительно указывать не стоит - при любых изменениях придётся менять в двух местах, что неизбежно приведёт к тому, что где-то что-то забудется и разойдётся

2024-01-04 00:10 UTC, Arsennikum commented on mycustomerror.py
> +        """Инициализация объекта MyCustomError."""
очевидные комменты лучше не добавлять, они засоряют код

2024-01-04 00:10 UTC, Arsennikum commented on mycustomerror.py
> +        print('Вызов метода str MyCustomError')
Как и этот print, это наверное было для дебага?

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
а в virtualenv как-то можно разграничить переменные окружения?
Ситуация такая: на серваке будут запускаться несколько ботов. Не в докере, все вместе просто на одном серваке. Соответвенно, если у них будет общее env окружение, то нужно добавить префикс для переменных. Либо возможно если у каждого свой virtualenv, то и переменные окружения будут заизолированы? Или это как-то может через .env можно сделать?

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    return telegram_chat_id
Тут сразу несколько моментов)

- не ..._id, а .._ids, их же список. Либо .._id_list
- для парсинга строки по запятым наверняка есть встроенная функция
- в принципе мониторинг не критичная вещь и по id'шникам не стоит заморачиваться. В итоге кто-то попросит бота, чтобы смотреть тоже доступность сайтов - придётся открывать сервак и править id-шники, за этим списком следить и т.п. Поэтому предлагаю сделать обычную модель бота - человек отправляет /start, (можно, но не обязательно ещё какой-нибудь /subscribe) - и ему приходят оповещения о падениях. Кто подписался - можно хранить в файлике на диске. Если конечно телеграм не предоставляет в апишке список людей, стартанувших бота

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    else:
Дублирование, излишняя вложенность

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    bot = Bot(token=TELEGRAM_TOKEN)
Почему бот инициализируется именно здесь? Неочевидно и завязка, что именно этот метод должен вызваться первым. Лучше перенести в main()

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    status_bank = ''
логика со status_bank вообще не понятна. Здесь она всегда обнуляется, то есть дальше оно всегда '' - но зачем-то сравнивается

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +                current_timestamp = 1646906700
а это что и зачем? оно не используется)

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +            except ConnectionError as conerror:
ConnectionError может быть например при неверном dns ответе - что тоже случается у нас, когда хостинг делает какие-то переносы или мы переносим домены и что-то из этого разъезжается. И это вполне себе причина недоступности, которую нужно сообщать всем, а не только одному админу. И с указанием сайта

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    bot = Bot(token=TELEGRAM_TOKEN)
увидел, что в майне это итак есть, а здесь дублируется, выходит)

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +    else:
после sys.exit уже ничего не произойдёт, так что можно убрать ветку else, заодно уберётся излишняя вложенность) 
(важно не допускать callback hell и уменьшать вложенность везде по возможности)

2024-01-04 00:10 UTC, Arsennikum commented on bot.py
> +                    get_resource_answer(current_timestamp, endp)
этот метод явно не является get resource answer. Это либо check resource, либо если get, то оно тогда должна возвращать, и не answer, а status code, судя по реализации - а логика проверки этого статуса уже тогда должна происходить здесь

2024-01-04 12:03 UTC, vasiliy-kotov commented on setup.cfg
> +max-complexity = 10
Скорректировал.

2024-01-04 12:03 UTC, vasiliy-kotov commented on README.md
> +Перечень зависимостей:
Скорректировал.

2024-01-04 12:03 UTC, vasiliy-kotov commented on mycustomerror.py
> +        """Инициализация объекта MyCustomError."""
Скорректировал.

2024-01-04 12:03 UTC, vasiliy-kotov commented on mycustomerror.py
> +        print('Вызов метода str MyCustomError')
Скорректировал.

2024-01-04 12:18 UTC, vasiliy-kotov commented on bot.py
> +    status_bank = ''
Ошибочно оставленный код из другого бота. Вырезал и поправил связанные блоки.

2024-01-04 12:18 UTC, vasiliy-kotov commented on bot.py
> +                current_timestamp = 1646906700
Ошибочно оставленный код из другого бота. Вырезал.

2024-01-04 13:37 UTC, Arsennikum commented on bot.py
> +                    get_resource_answer(current_timestamp, endp)
Кстати предполагал, что будет отдельная команда бота, которая покажет статус последней проверки по всем сайтам. Можно пока такое не делать, но добавь хотя бы команду типа /info, которая покажет, что сам бот активен, и ещё можно вывести по ней текущие настройки (список проверяемых сайтов и как часто происходит проверка)

2024-01-24 03:40 UTC, vasiliy-kotov commented on setup.cfg
> +max-complexity = 10
Скорректировано.

2024-01-24 03:41 UTC, vasiliy-kotov commented on README.md
> +Перечень зависимостей:
Скорректировано.

2024-01-24 03:41 UTC, vasiliy-kotov commented on mycustomerror.py
> +        """Инициализация объекта MyCustomError."""
Скорректировано, однако Flake8 говорит: Missing docstring in __init__Flake8(D107).

2024-01-24 03:41 UTC, vasiliy-kotov commented on mycustomerror.py
> +        print('Вызов метода str MyCustomError')
Скорректировано.

2024-01-24 03:41 UTC, vasiliy-kotov commented on bot.py
> +    status_bank = ''
Ошибочно оставленный код из другого бота. Вырезал и поправил связанные блоки.

2024-01-24 03:41 UTC, vasiliy-kotov commented on bot.py
> +                current_timestamp = 1646906700
Ошибочно оставленный код из другого бота. Вырезал и поправил связанные блоки.

2024-01-24 03:41 UTC, vasiliy-kotov commented on bot.py
> +            except ConnectionError as conerror:
Скорректировал.

2024-01-24 03:42 UTC, vasiliy-kotov commented on bot.py
> +    else:
Скорректировал.

2024-01-24 03:43 UTC, vasiliy-kotov commented on bot.py
> +                    get_resource_answer(current_timestamp, endp)
По первому нужно только переименовать или также изменить логику?

По второму добавил 2 кнопки: проверка последнего статуса (храниться в переменной с указанием даты и времени) и настройки.

2024-01-25 11:28 UTC, Arsennikum commented on mycustomerror.py
> +        """Инициализация объекта MyCustomError."""
Это тогда нужно смотреть, как принято в python. Вообще бэст практис - писать "самодокументируемый" код, где не нужно писать (много) комментов.
Возможно flake8 нужно настроить

2024-01-28 15:59 UTC, vasiliy-kotov commented on bot.py
> +    return telegram_chat_id
1. Скорректировал.
2. Действительно есть. Скорректировал.
3. Скорректировал.

2024-01-28 15:59 UTC, vasiliy-kotov commented on bot.py
> +    else:
Если речь про ветку else, то убрал.

2024-01-28 15:59 UTC, vasiliy-kotov commented on bot.py
> +    bot = Bot(token=TELEGRAM_TOKEN)
Скорректировал.

2024-02-03 14:00 UTC, zomlik commented on bot.py
> +        raise MyCustomError(message)
Как происходит отправка сообщения админу в этой функции ?

2024-02-03 14:00 UTC, zomlik commented on bot.py
> +                    f.close()
Как я понимаю, оператор with автоматически вызывает метод close(), поэтому нет необходимости вручную вызывать его

2024-02-03 14:58 UTC, Arsennikum requested changes
Ещё немного)

2024-02-03 14:58 UTC, Arsennikum commented on README.md
> +- TELEGRAM_CHAT_ID в формате <id_1,id_2,id_n>,
похоже реализация расходится с документацией)

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    logger.info('Читаем файл list_tg_ids.txt.')
такие логи скорее под debug лучше помещать

2024-02-03 14:58 UTC, Arsennikum commented on list_tg_ids.txt
> +TELEGRAM_SUBSCRIBER_IDS=341070290,515611592
это скорее .properties файл

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +                ids = line[line.find('=') + 1:]
немного странноватая логика с нахождением = и дальше принимать, что это только ид-шники. Вообще это же проперти, их лучше сразу читать с помощью jproperties или ConfigParser. Тогда сюда можно в один файлик будет и список сайтов прописать и id админа и легко их считать

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +def get_telegram_id():
я бы назвал скорее get_subscribers_ids
Сразу понятно, что их несколько и что это подписчики бота. Т.к. это изначально телеграм бот, писать именно telegram в названии - избыточно

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    запрос и, если статус ответа на 200, то посылает сообщение пользоватлю из
не* 200

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    logger.setLevel(logging.DEBUG)
я думаю такое должно задаваться где-то в пропертях или env, без изменения исходников) И следующая строка тоже

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    logger.info('Формат записей:\n%(asctime)s - %(levelname)s - %(message)s -'
это излишне

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    logger.info('********************\nНачало журнала.')
Не особо осмысленная информация) Можно хотя бы тогда "Старт работы бота проверки ресурсов ОД"

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +
А нельзя здесь сразу `SUBSCRIBER_IDS_LIST = get_subscribers_ids()`?

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    global RESULTS
Немного неясное название. Скорее CHECK_RESULT_TEXT или типа того

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +            RESULTS.append(f'Дата и время последней проверки - {DT_MOSCOW}.\n')
а где очищается results?

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +        for i in range(0, len(TELEGRAM_SUBSCRIBER_IDS_LIST)):
вроде как есть простой способ удаления из списка, без перебора всех элементов) https://stackoverflow.com/a/2793341

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    def min_or_hour(amount_time):
здесь тоже можно проще https://stackoverflow.com/a/538721

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    button = ReplyKeyboardMarkup(
это похоже дублируется

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +    message = last_check_message(RESULTS)
а не проще ли message = " ".join(RESULTS)?

2024-02-03 14:58 UTC, Arsennikum commented on bot.py
> +RETRY_TIME = 14400  # В секундах
и если сделаешь общие проперти, вот эти все константы тоже классно будет вынести в них

2024-02-18 15:37 UTC, vasiliy-kotov commented on bot.py
> +
Для этого функция должна будет быть выше констант, которые по code style должны быть в начале файла.

2024-05-10 06:51 UTC, Arsennikum approved these changes

2024-05-10 06:51 UTC, Arsennikum commented on bot.py
> +    tg_setting['subscription_tg_ids'] = new_tg_setting
Судя по всему (https://stackoverflow.com/a/33270082/4906544) можно сделать так
```suggestion
    if tg_id in telegram_ids:
            telegram_ids.remove(tg_id)
            message = ('Вы отписались от рассылки сообщений от бота.')
            logger.info(f'Пользователь {name} отписывается от рассылки.')
    else:
            telegram_ids.append(tg_id)
            message = ('Вы подписались на рассылку сообщений от бота.')
            logger.info(f'Пользователь {name} подписывается на рассылку.')
    tg_setting['subscription_tg_ids'] = ".".join( str(id) for id in telegram_ids )
```

2024-05-10 06:51 UTC, Arsennikum commented on bot.py
> +    else:
я бы здесь переписал без if и без передачи бота в параметры (бот же один, зачем его здесь прокидывать)
```suggestion
BOT = Bot(token=TELEGRAM_TOKEN)

def get_bot():
    if not BOT:
        message = f'Ошибка инициализации объекта bot - {bot}.'
        logger.error(message, exc_info=True)
        raise MyCustomError(message)
    return BOT

def send_message(message, telegram_ids):
    """Отправляет сообщение в Telegram-чаты участников процесса."""
    bot = get_bot()
```
И этот метод можно будет использовать в send_message_admin аналогично

2024-05-10 06:53 UTC, Arsennikum commented on bot.py
> +    message = ''.join(CHECK_RESULT)
а нужен ли здесь .join? он же ничего не делает. Может просто
```suggestion
    message = CHECK_RESULT
```
или вообще избавиться от лишней переменной

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    logger.info('Читаем файл list_tg_ids.txt.')
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +                ids = line[line.find('=') + 1:]
Ид-шники сделал в файле .cfg.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +                ids = line[line.find('=') + 1:]
id админ сделал в файле .cfg.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +                ids = line[line.find('=') + 1:]
список сайтов сделал в файле .cfg.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +        raise MyCustomError(message)
Ошибка. Никак. Исправил.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    запрос и, если статус ответа на 200, то посылает сообщение пользоватлю из
Исправил.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    message = last_check_message(RESULTS)
Проще. Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +        for i in range(0, len(TELEGRAM_SUBSCRIBER_IDS_LIST)):
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +                    f.close()
Верно. Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    global RESULTS
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +            RESULTS.append(f'Дата и время последней проверки - {DT_MOSCOW}.\n')
Добавил.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    logger.info('********************\nНачало журнала.')
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    logger.info('Формат записей:\n%(asctime)s - %(levelname)s - %(message)s -'
Убрал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on list_tg_ids.txt
> +TELEGRAM_SUBSCRIBER_IDS=341070290,515611592
Сделал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    button = ReplyKeyboardMarkup(
Оптимизировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    logger.setLevel(logging.DEBUG)
Выполнил.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +
Убрал константу за ненадобностью.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
Pipenv создаёт отдельные вирт. окружения для каждого проекта, переменные которых доступны в рамках отдельного окружения.

2024-05-13 19:09 UTC, vasiliy-kotov commented on README.md
> +- TELEGRAM_CHAT_ID в формате <id_1,id_2,id_n>,
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on list_tg_ids.txt
> +TELEGRAM_SUBSCRIBER_IDS=341070290,515611592
Перенёс в файл setup.cfg.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +            RESULTS.append(f'Дата и время последней проверки - {DT_MOSCOW}.\n')
Переименовал константу на CHECK_RESULT.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    def min_or_hour(amount_time):
Удалил эту функцию и заменил другой логикой - см. переменную `date_time`.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +def get_telegram_id():
Скорректировал.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +RETRY_TIME = 14400  # В секундах
Сделал в файле setup.cfg.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +        raise MyCustomError(message)
Сделал комит с исправлениями.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    message = ''.join(CHECK_RESULT)
Согласен. Убрал join.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    message = ''.join(CHECK_RESULT)
Нет, вернул. Без этого список не конвертируется в строку и некорректно применяется кодировка.

2024-05-13 19:09 UTC, vasiliy-kotov commented on bot.py
> +    tg_setting['subscription_tg_ids'] = new_tg_setting
Согласен. Скорректировал, но вместо разделителя точки указал запятую.

2024-05-14 10:56 UTC, merged